import type { Server } from 'socket.io'; import type { Logger } from 'pino';
import { authenticate, rpc, type JsonRow } from './database.js'; import { cashoutSchema, commandAck, placeBetSchema, readHandshakeToken, syncSchema } from './contracts.js'; import { config } from './config.js'; import { envelope } from './envelope.js'; import type { Sequencer } from './sequencer.js';
import type { RateLimiter } from './rateLimit.js'; import { commandLatency,commands,connections } from './metrics.js';
export function installSocket(io:Server,seq:Sequencer,log:Logger,limiter:RateLimiter){const nsp=io.of('/crash');nsp.use(async(socket,next)=>{try{const token=readHandshakeToken(socket.handshake.auth);const auth=await authenticate(token);const maxPlayers=await rpc<number>(auth.db,'get_crash_connection_limit',{p_game_id:config.CRASH_GAME_ID,p_table_id:config.CRASH_TABLE_ID});if(!await limiter.enterConnection(config.CRASH_TABLE_ID,socket.id,Number(maxPlayers||1)))return next(new Error('TABLE_FULL'));socket.data.connectionCounted=true;socket.data.userId=auth.user.id;socket.data.db=auth.db;next()}catch(error){log.warn({error},'crash socket handshake rejected');next(new Error('UNAUTHORIZED'))}});nsp.on('connection',async(socket)=>{connections.inc();const userId=String(socket.data.userId);const presenceTimer=setInterval(()=>void limiter.refreshConnection(config.CRASH_TABLE_ID,socket.id),30_000);socket.join(`user:${userId}`);socket.join(`crash:${config.CRASH_TABLE_ID}`);socket.emit('session:ready',await envelope(seq,config.CRASH_TABLE_ID,null,{userId,connected:true}));
 const safe=async(type:string,requestId:string,ack:Function,work:()=>Promise<JsonRow>)=>{if(!await limiter.allow(`${type}:${userId}`,type==='sync'?10:20,10)){commands.inc({type,result:'rate_limited'});return ack({requestId,accepted:false,code:'RATE_LIMITED',roundRevision:0,result:{}})}const end=commandLatency.startTimer({type});try{const result=commandAck(requestId,await work());commands.inc({type,result:result.accepted?'accepted':'rejected'});ack(result)}catch(error){commands.inc({type,result:'error'});log.warn({error,userId},'command failed');ack({requestId,accepted:false,code:'SERVER_ERROR',roundRevision:0,result:{}})}finally{end()}};
 socket.on('state:sync',async(input,ack=()=>{})=>{const parsed=syncSchema.safeParse(input);if(!parsed.success)return ack({accepted:false,code:'INVALID_PAYLOAD'});if(!await limiter.allow(`sync:${userId}`,10,10))return ack({accepted:false,code:'RATE_LIMITED'});try{const snap=await rpc(socket.data.db,'get_crash_snapshot',{p_game_id:config.CRASH_GAME_ID,p_table_id:config.CRASH_TABLE_ID,p_known_version:null});const message=await envelope(seq,config.CRASH_TABLE_ID,snap.round?.id||null,{});message.payload={...snap,connected:true,sequence:message.sequence};socket.emit('crash:snapshot',message);ack({accepted:true,code:'OK'})}catch{ack({accepted:false,code:'SYNC_FAILED'})}});
 socket.on('bet:place',(input,ack=()=>{})=>{const p=placeBetSchema.safeParse(input);if(!p.success)return ack({requestId:input?.requestId||'',accepted:false,code:'INVALID_PAYLOAD',roundRevision:0,result:{}});void safe('place',p.data.requestId,ack,()=>rpc(socket.data.db,'place_crash_bet',{p_round_id:p.data.roundId,p_request_id:p.data.requestId,p_amount:p.data.amount,p_auto_cashout_bp:p.data.autoCashoutBp??null}))});
 socket.on('bet:cashout',(input,ack=()=>{})=>{const p=cashoutSchema.safeParse(input);if(!p.success)return ack({requestId:input?.requestId||'',accepted:false,code:'INVALID_PAYLOAD',roundRevision:0,result:{}});void safe('cashout',p.data.requestId,ack,()=>rpc(socket.data.db,'cash_out_crash_bet',{p_round_id:p.data.roundId,p_bet_id:p.data.betId,p_request_id:p.data.requestId}))});
 socket.on('ping',(input,ack=()=>{})=>ack({clientTime:input?.clientTime,serverTime:new Date().toISOString()}));socket.on('disconnect',()=>{clearInterval(presenceTimer);connections.dec();if(socket.data.connectionCounted)void limiter.leaveConnection(config.CRASH_TABLE_ID,socket.id)});});return nsp;}
