-- 115_device_push_tokens.sql
-- ============================================================
-- Firebase Cloud Messaging device-token registry.
--
-- Why a separate table instead of storing one token on profiles?
--   - One user may sign in on multiple devices.
--   - Tokens rotate and can be invalidated independently.
--   - Push senders usually need an active-token list, not a single
--     mutable field on the profile row.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.device_push_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  fcm_token   TEXT NOT NULL UNIQUE,
  platform    TEXT NOT NULL DEFAULT 'android' CHECK (platform IN ('android', 'ios')),
  device_name TEXT,
  app_build   TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_device_push_tokens_user_token
  ON public.device_push_tokens (user_id, fcm_token);

CREATE INDEX IF NOT EXISTS idx_device_push_tokens_active_user
  ON public.device_push_tokens (user_id, is_active);

ALTER TABLE public.device_push_tokens ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.register_my_push_token(
  p_fcm_token   TEXT,
  p_platform    TEXT DEFAULT 'android',
  p_device_name TEXT DEFAULT NULL,
  p_app_build   TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  me UUID := auth.uid();
BEGIN
  IF me IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF COALESCE(BTRIM(p_fcm_token), '') = '' THEN
    RAISE EXCEPTION 'Missing FCM token';
  END IF;

  INSERT INTO public.device_push_tokens (
    user_id,
    fcm_token,
    platform,
    device_name,
    app_build,
    is_active,
    updated_at,
    last_seen_at
  )
  VALUES (
    me,
    p_fcm_token,
    COALESCE(NULLIF(BTRIM(p_platform), ''), 'android'),
    NULLIF(BTRIM(p_device_name), ''),
    NULLIF(BTRIM(p_app_build), ''),
    TRUE,
    NOW(),
    NOW()
  )
  ON CONFLICT (fcm_token) DO UPDATE
    SET user_id      = EXCLUDED.user_id,
        platform     = EXCLUDED.platform,
        device_name  = EXCLUDED.device_name,
        app_build    = EXCLUDED.app_build,
        is_active    = TRUE,
        updated_at   = NOW(),
        last_seen_at = NOW();

  RETURN jsonb_build_object('success', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.register_my_push_token(TEXT, TEXT, TEXT, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.unregister_my_push_token(
  p_fcm_token TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  me UUID := auth.uid();
BEGIN
  IF me IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF COALESCE(BTRIM(p_fcm_token), '') = '' THEN
    RETURN jsonb_build_object('success', false, 'message', 'Missing FCM token');
  END IF;

  UPDATE public.device_push_tokens
     SET is_active = FALSE,
         updated_at = NOW()
   WHERE user_id = me
     AND fcm_token = p_fcm_token;

  RETURN jsonb_build_object('success', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.unregister_my_push_token(TEXT) TO authenticated;
