import { build } from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const result = await build({
  entryPoints: [path.join(root, 'games/main.ts')],
  bundle: true,
  write: false,
  minify: true,
  legalComments: 'none',
  target: ['chrome90'],
  format: 'iife',
  platform: 'browser',
  loader: { '.webp': 'dataurl' },
  define: { 'process.env.NODE_ENV': '"production"' },
});

const javascript = result.outputFiles[0].text.replaceAll('</script>', '<\\/script>');
const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob: https:; font-src data:; media-src 'none'; connect-src 'none'; worker-src blob:">
  <style>
    html,body,#game-root{width:100%;height:100%;margin:0;overflow:hidden;background:#090b18;touch-action:none;-webkit-user-select:none;user-select:none}
    canvas{display:block;outline:none}
  </style>
</head>
<body>
  <div id="game-root"></div>
  <script>window.__GAME_ID__="__GAME_ID_VALUE__";</script>
  <script>${javascript}</script>
</body>
</html>`;

const output = path.join(root, 'src/game-platform/generated/GameBundle.ts');
await fs.mkdir(path.dirname(output), { recursive: true });
await fs.writeFile(output, `// Generated by scripts/build-games.mjs. Do not edit manually.\nexport const GAME_HTML = ${JSON.stringify(html)};\n`);
console.log(`Built Phaser game platform: ${(Buffer.byteLength(html) / 1024 / 1024).toFixed(2)} MB`);
